version: '3'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017 # physical port:container port
    environment:
      MONGO_DATABASE: ${MONGODB_NAME}
    volumes:
      - ./mongo:/data/db
